name: Gitops pipeline with Argocd

on:
  push:
      branches:
            - main
env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
               
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'
                  
            - name: Install Node.js dependencies
              run: npm install
              
            - name: Set short Git SHA
              run: echo "GIT_HASH=$(echo $GITHUB_SHA | cut -c1-5)" >> $GITHUB_ENV

            - name: Build Docker image
              env:
                DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
              #run: docker build -t dungda7/app01:$GIT_HASH .
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app01:$GIT_HASH .
              
            - name: Log in to DockerHub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              
            - name: Push Docker image to DockerHub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app01:$GIT_HASH
            
      
